# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'gurunaviapi' do
 pod 'Alamofire'
 pod 'SwiftyJSON'
 pod 'SDWebImage'
end

target 'gurunaviapiTests' do

end

target 'gurunaviapiUITests' do

end

